Fix aside menu
chrislopresto/ember-freestyle pull request #827
Opened 2022-09-01 12:58 UTC by KamiKillertO

There's currently an issue with the aside menu button in the live demo app.
![image](https://user-images.githubusercontent.com/9579729/187918760-f9d14dad-9b14-4a36-8e5c-d658e4f4c420.png)

When we click on it, we are redirected to the documentation home page.
With this fix the aside menu button will now works as expected, when clicking on it it will open the side menu
![image](https://user-images.githubusercontent.com/9579729/187919283-6ed061b0-3faf-4288-9aeb-03a8ef29ea69.png)

I've also added a focus trap when the menu is opened

2022-09-01 13:32 UTC, lukemelia commented
Hi @KamiKillertO Thanks for working on this. It looks like linting is failing on this PR. Can you fix that?

2022-09-01 14:36 UTC, KamiKillertO commented
Sorry for that 😅

2022-09-02 06:48 UTC, KamiKillertO commented
@lukemelia Done 👍

2022-09-06 10:04 UTC, bertdeblock requested changes

2022-09-06 10:04 UTC, bertdeblock commented on package.json
> +    "ember-focus-trap": "^1.0.1",
This has to go in `dependencies`.

2022-09-08 07:37 UTC, KamiKillertO commented on package.json
> +    "ember-focus-trap": "^1.0.1",
Done 👍

2022-09-09 18:02 UTC, bertdeblock approved these changes

2022-09-09 18:49 UTC, bertdeblock commented
Seems there's still a conflict. Probably because I merged https://github.com/chrislopresto/ember-freestyle/pull/836, sorry for that. Looks good to go otherwise!

2022-09-12 20:47 UTC, merged

2022-09-15 07:20 UTC, bertdeblock commented
We're running into https://github.com/embroider-build/embroider/issues/1175 because of the `ember-focus-trap` addition. This isn't an issue with `ember-freestyle` itself, but just wanted to point out that this change might break people's Embroider based builds.

2022-09-15 14:18 UTC, lukemelia commented
@bertdeblock What is the ideal resolution from your perspective?

2022-09-16 06:08 UTC, bertdeblock commented
Other than fixing https://github.com/embroider-build/embroider/issues/1175, I'm not sure to be honest.
The current workaround seems to be for the host app to install `ember-focus-trap` as well.
We could create an issue in `ember-freestyle` explaining this or even have this documented in the README or something until the bug is fixed. The only downside I guess is, we recommend to exclude `ember-freestyle` for production builds. If the host app itself doesn't use `ember-focus-trap` they end up with unused code in production builds unless they exclude `ember-focus-trap` manually themselves.

2022-11-14 08:47 UTC, bertdeblock commented
FYI, https://github.com/embroider-build/embroider/pull/1278 should fix this issue for us.